version: '3.9'
services:

  mongodb:
    image: mongo:5.0.5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - db:/var/lib/mongodb/data
    restart: always
    ports:
      - "${MONGODB_LOCAL_PORT}:${MONGODB_DOCKER_PORT}"

  
  web:
    build: .
    environment:
      - PORT=${NODE_LOCAL_PORT}
      - DB_HOST=mongodb
      - DB_USER=${MONGODB_USER}
      - DB_PASSWORD=${MONGODB_PASSWORD}
      - DB_NAME=${MONGODB_DATABASE}
      - DB_PORT=${MONGODB_DOCKER_PORT}
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    restart: always
    depends_on:
      - mongodb


volumes:
  db:



    
      

